[
   Yuml                                     -- _1,
   Yuml.1:iter-star                         -- _1,
   YumlEntity                               -- KW["["] _1 _2 KW["]"],
   EntityDefinition                         -- _1,
   EntityDefinition.1:iter-star             -- _1,
   EntityDefinition.1:iter-star.1:alt       -- _1 _2,
   EntityMemberGroup                        -- _1 _2,
   EntityMemberGroup.2:iter-star            -- _1,
   EntityMembers                            -- _1 _2,
   EntityMembers.2:iter-star                -- _1,
   EntityMembers.2:iter-star.1:seq          -- _1 _2,
   EntityMember                             -- _1,
   EntityMember.1:alt                       -- _1 _2,
   EntitiesRelation                         -- _1 _2 _3,
   MultipleEntitiesRelation                 -- _1 _2,
   MultipleEntitiesRelation.2:iter          -- _1,
   MultipleEntitiesRelation.2:iter.1:seq    -- _1 _2,
   Note                                     -- KW["["] _1 _2 _3 KW["]"],
   Note.3:opt                               -- _1,
   BGColor                                  -- KW["{"] _1 KW[":"] _2 KW["}"],
   DeclarationSepeartor                     -- _1,
   MemberGroupSeperator                     -- _1,
   MemberSeperator                          -- _1,
   AssociationOperator                      -- _1 _2 _3,
   InheritenceOperator                      -- _1,
   LeftAssociation                          -- _1,
   LeftAssociation.1:iter-star              -- _1,
   LeftAssociation.1:iter-star.1:alt        -- _1 _2,
   LeftAssociation.1:iter-star.1:alt.2:alt  -- _1 _2,
   RightAssociation                         -- _1,
   RightAssociation.1:iter-star             -- _1,
   RightAssociation.1:iter-star.1:alt       -- _1 _2,
   RightAssociation.1:iter-star.1:alt.2:alt -- _1 _2,
   LeftDirectonalOperator                   -- _1,
   AggregationOperator                      -- _1,
   CompositionOperator                      -- _1,
   RightDirectionalOperator                 -- _1,
   AggregationOperator                      -- _1,
   CompositionOperator                      -- _1,
   Connector                                -- _1,
   Connector                                -- _1,
   SimpleCardinality                        -- _1,
   SimpleCardinality                        -- _1,
   RangeCardinality                         -- _1 _2 _3,
   CardinalityConnector                     -- _1,
   Label                                    -- _1,
   EntityProperty                           -- _1,
   EntityMethod                             -- _1
]