[
   aliases                                                        -- KW["aliases"] _1,
   alias                                                          -- _1 KW["->"] _2,
   char-class                                                     -- _1,
   seq                                                            -- _1 KW["."] _2,
   single                                                         -- _1,
   alt                                                            -- _1 KW["|"] _2,
   list                                                           -- KW["[["] _1 KW["]]"],
   list.1:iter-star-sep                                           -- _1 KW[","],
   follow                                                         -- _1 KW["-/-"] _2,
   restrictions                                                   -- KW["restrictions"] _1,
   reject                                                         -- KW["reject"],
   prefer                                                         -- KW["prefer"],
   avoid                                                          -- KW["avoid"],
   quoted                                                         -- _1,
   unquoted                                                       -- _1,
   label                                                          -- _1 KW[":"] _2,
   unquoted-fun                                                   -- _1,
   quoted-fun                                                     -- _1,
   lit                                                            -- _1,
   ci-lit                                                         -- _1,
   prefix-fun                                                     -- _1 KW["("] _2 KW[")"] KW["->"] _3 _4,
   prefix-fun.2:iter-star-sep                                     -- _1 KW[","],
   kernel-start-symbols                                           -- KW["start-symbols"] _1,
   lexical-start-symbols                                          -- KW["lexical"] KW["start-symbols"] _1,
   context-free-start-symbols                                     -- KW["context-free"] KW["start-symbols"] _1,
   sort                                                           -- _1,
   parameterized-sort                                             -- _1 KW["[["] _2 KW["]]"],
   parameterized-sort.2:iter-sep                                  -- _1 KW[","],
   sorts                                                          -- KW["sorts"] _1,
   numeric                                                        -- _1,
   short                                                          -- _1,
   top                                                            -- KW["\\TOP"],
   eof                                                            -- KW["\\EOF"],
   bot                                                            -- KW["\\BOT"],
   label_start                                                    -- KW["\\LABEL_START"],
   range                                                          -- _1 KW["-"] _2,
   conc                                                           -- _1 _2,
   absent                                                         -- ,
   present                                                        -- _1,
   simple-charclass                                               -- KW["["] _1 KW["]"],
   comp                                                           -- KW["~"] _1,
   diff                                                           -- _1 KW["/"] _2,
   isect                                                          -- _1 KW["/\\"] _2,
   union                                                          -- _1 KW["\\/"] _2,
   char-class                                                     -- _1,
   left                                                           -- KW["left"],
   right                                                          -- KW["right"],
   non-assoc                                                      -- KW["non-assoc"],
   assoc                                                          -- KW["assoc"],
   bracket                                                        -- KW["bracket"],
   assoc                                                          -- _1,
   default                                                        -- KW["<"] _1 KW[">"],
   default.1:iter-sep                                             -- _1 KW[","],
   with-arguments                                                 -- _1 _2,
   non-transitive                                                 -- _1 KW["."],
   simple-group                                                   -- _1,
   prods-group                                                    -- KW["{"] _1 KW["}"],
   assoc-group                                                    -- KW["{"] _1 KW[":"] _2 KW["}"],
   chain                                                          -- _1,
   chain.1:iter-sep                                               -- _1 KW[">"],
   assoc                                                          -- _1 _2 _3,
   priorities                                                     -- KW["priorities"] _1,
   lifting                                                        -- KW["`"] _1 KW["`"],
   empty                                                          -- KW["("] KW[")"],
   seq                                                            -- KW["("] _1 _2 KW[")"],
   seq.2:iter                                                     -- _1,
   opt                                                            -- _1 KW["?"],
   iter                                                           -- _1 KW["+"],
   iter-star                                                      -- _1 KW["*"],
   iter-sep                                                       -- KW["{"] _1 _2 KW["}"] KW["+"],
   iter-star-sep                                                  -- KW["{"] _1 _2 KW["}"] KW["*"],
   tuple                                                          -- KW["<"] _1 KW[","] _2 KW[">"],
   tuple.2:iter-sep                                               -- _1 KW[","],
   func                                                           -- KW["("] _1 KW["=>"] _2 KW[")"],
   alt                                                            -- _1 KW["|"] _2,
   strategy                                                       -- KW["("] _1 KW["->"] _2 KW[")"],
   renamings                                                      -- V  [V vs=2 [KW["["] _1] KW["]"]],
   renamings.1:iter-star                                          -- _1,
   symbol                                                         -- _1 KW["=>"] _2,
   production                                                     -- _1 KW["=>"] _2,
   module                                                         -- KW["module"] _1 _2 _3,
   module.2:iter-star                                             -- _1,
   exports                                                        -- KW["exports"] _1,
   hiddens                                                        -- KW["hiddens"] _1,
   unparameterized                                                -- _1,
   parameterized                                                  -- _1 KW["["] _2 KW["]"],
   id                                                             -- KW["id"] KW["("] _1 KW[")"],
   imports                                                        -- KW["imports"] _1,
   imp-section                                                    -- _1,
   module                                                         -- _1,
   renamed-module                                                 -- _1 _2,
   lexical-syntax                                                 -- KW["lexical"] KW["syntax"] _1,
   context-free-syntax                                            -- KW["context-free"] KW["syntax"] _1,
   variables                                                      -- KW["variables"] _1,
   lexical-variables                                              -- KW["lexical"] KW["variables"] _1,
   cf                                                             -- KW["<"] _1 KW["-CF"] KW[">"],
   lex                                                            -- KW["<"] _1 KW["-LEX"] KW[">"],
   varsym                                                         -- KW["<"] _1 KW["-VAR"] KW[">"],
   layout                                                         -- KW["LAYOUT"],
   empty-grammar                                                  -- KW["(/)"],
   conc-grammars                                                  -- _1 _2,
   present                                                        -- KW["e"] _1,
   absent                                                         -- ,
   real-con                                                       -- _1 KW["."] _2 _3,
   natural                                                        -- _1,
   positive                                                       -- KW["+"] _1,
   negative                                                       -- KW["-"] _1,
   quoted                                                         -- _1,
   unquoted                                                       -- _1,
   int                                                            -- _1,
   real                                                           -- _1,
   fun                                                            -- _1,
   appl                                                           -- _1 KW["("] _2 KW[")"],
   appl.2:iter-sep                                                -- _1 KW[","],
   placeholder                                                    -- KW["<"] _1 KW[">"],
   list                                                           -- KW["["] _1 KW["]"],
   list.1:iter-star-sep                                           -- _1 KW[","],
   annotated                                                      -- _1 _2,
   default                                                        -- KW["{"] _1 KW["}"],
   default.1:iter-sep                                             -- _1 KW[","],
   default                                                        -- _1,
   term                                                           -- _1,
   attrs                                                          -- KW["{"] _1 KW["}"],
   attrs.1:iter-star-sep                                          -- _1 KW[","],
   no-attrs                                                       -- ,
   prod                                                           -- _1 KW["->"] _2 _3,
   syntax                                                         -- KW["syntax"] _1,
   start                                                          -- KW["<START>"],
   file-start                                                     -- KW["<Start>"],
   lexical-priorities                                             -- KW["lexical"] KW["priorities"] _1,
   context-free-priorities                                        -- KW["context-free"] KW["priorities"] _1,
   lexical-restrictions                                           -- KW["lexical"] KW["restrictions"] _1,
   context-free-restrictions                                      -- KW["context-free"] KW["restrictions"] _1,
   definition                                                     -- KW["definition"] _1,
   non-transitive                                                 -- _1 KW["."],
   OverlayNoArgs                                                  -- _1 KW["="] _2,
   Overlay                                                        -- _1 KW["("] _2 KW[")"] KW["="] _3,
   Overlay.2:iter-star-sep                                        -- _1 KW[","],
   DynRuleScope                                                   -- KW["{|"] _1 KW[":"] _2 KW["|}"],
   ScopeLabels                                                    -- KW["~"] _1,
   GenDynRules                                                    -- KW["rules"] KW["("] _1 KW[")"],
   GenDynRules.1:iter-star                                        -- _1,
   AddScopeLabel                                                  -- _1 KW["+"] _2,
   UndefineDynRule                                                -- _1 KW[":-"] _2,
   SetDynRule                                                     -- _1 KW[":"] _2,
   AddDynRule                                                     -- _1 KW[":+"] _2,
   SetDynRuleMatch                                                -- _1 KW[":"] _2,
   DynRuleAssign                                                  -- _1 KW[":="] _2,
   DynRuleAssignAdd                                               -- _1 KW[":+="] _2,
   SetDynRuleDepends                                              -- _1 KW[":"] _2 KW["depends"] KW["on"] _3,
   LabeledDynRuleId                                               -- _1 KW["."] _2,
   AddLabelDynRuleId                                              -- _1 KW["+"] _2,
   DynRuleId                                                      -- _1,
   LabeledDynRuleScopeId                                          -- _1 KW["."] _2,
   DynRuleScopeId                                                 -- _1,
   RDecNoArgs                                                     -- _1,
   RDec                                                           -- _1 KW["("] _2 KW[")"],
   RDec.2:iter-star-sep                                           -- _1 KW[","],
   RDecT                                                          -- _1 KW["("] _2 KW["|"] _3 KW[")"],
   RDecT.2:iter-star-sep                                          -- _1 KW[","],
   RDecT.3:iter-star-sep                                          -- _1 KW[","],
   RuleNames                                                      -- KW["~"] _1,
   DynRuleIntersectFix                                            -- KW["/"] _1 KW["\\*"] _2,
   DynRuleIntersect                                               -- _1 KW["/"] _2 KW["\\"] _3,
   DynRuleUnion                                                   -- _1 KW["\\"] _2 KW["/"] _3,
   DynRuleIntersectUnion                                          -- _1 KW["/"] _2 KW["\\"] _3 KW["/"] _4,
   RDefNoArgs                                                     -- _1 KW[":"] _2,
   AnnoDef                                                        -- _1 _2,
   AnnoDef.1:iter                                                 -- _1,
   RDef                                                           -- _1 KW["("] _2 KW[")"] KW[":"] _3,
   RDef.2:iter-star-sep                                           -- _1 KW[","],
   RDefT                                                          -- _1 KW["("] _2 KW["|"] _3 KW[")"] KW[":"] _4,
   RDefT.2:iter-star-sep                                          -- _1 KW[","],
   RDefT.3:iter-star-sep                                          -- _1 KW[","],
   RuleNoCond                                                     -- _1 KW["->"] _2,
   Rule                                                           -- _1 KW["->"] _2 KW["where"] _3,
   Rule                                                           -- _1 KW["->"] _2 _3,
   Rule.3:iter                                                    -- _1,
   WhereClause                                                    -- KW["where"] _1,
   WithClause                                                     -- KW["with"] _1,
   SDefNoArgs                                                     -- _1 KW["="] _2,
   SDef                                                           -- _1 KW["("] _2 KW[")"] KW["="] _3,
   SDef.2:iter-star-sep                                           -- _1 KW[","],
   DefaultVarDec                                                  -- _1,
   Call                                                           -- _1 KW["("] _2 KW[")"],
   Call.2:iter-star-sep                                           -- _1 KW[","],
   ScopeDefault                                                   -- KW["{"] _1 KW["}"],
   BA                                                             -- _1 _2,
   LChoice                                                        -- _1 KW["<+"] _2,
   Rec                                                            -- KW["rec"] _1 KW["("] _2 KW[")"],
   Not                                                            -- KW["not"] KW["("] _1 KW[")"],
   Where                                                          -- KW["where"] KW["("] _1 KW[")"],
   With                                                           -- KW["with"] KW["("] _1 KW[")"],
   Test                                                           -- KW["test"] KW["("] _1 KW[")"],
   PrimNoArgs                                                     -- KW["prim"] KW["("] _1 KW[")"],
   Prim                                                           -- KW["prim"] KW["("] _1 KW[","] _2 KW[")"],
   Prim.2:iter-star-sep                                           -- _1 KW[","],
   StrCong                                                        -- _1,
   IntCong                                                        -- _1,
   RealCong                                                       -- _1,
   CharCong                                                       -- _1,
   CongQ                                                          -- _1 KW["("] _2 KW[")"],
   CongQ.2:iter-star-sep                                          -- _1 KW[","],
   AnnoCong                                                       -- _1 _2,
   StrategyCurly                                                  -- KW["{"] _1 KW["}"],
   EmptyTupleCong                                                 -- KW["("] KW[")"],
   TupleCong                                                      -- KW["("] _1 KW[","] _2 KW[")"],
   TupleCong.2:iter-sep                                           -- _1 KW[","],
   ListCongNoTail                                                 -- KW["["] _1 KW["]"],
   ListCongNoTail.1:iter-star-sep                                 -- _1 KW[","],
   ListCong                                                       -- KW["["] _1 KW["|"] _2 KW["]"],
   ListCong.1:iter-star-sep                                       -- _1 KW[","],
   ExplodeCong                                                    -- _1 KW["#"] _2,
   CallNoArgs                                                     -- _1,
   LRule                                                          -- KW["\\"] _1 KW["\\"],
   SRule                                                          -- KW["("] _1 KW[")"],
   Choice                                                         -- _1 KW["+"] _2,
   RChoice                                                        -- _1 KW["+>"] _2,
   Proceed                                                        -- KW["proceed"] KW["("] _1 KW[")"],
   Proceed.1:iter-sep                                             -- _1 KW[","],
   CondChoice                                                     -- KW["if"] _1 KW["then"] _2 KW["else"] _3 KW["end"],
   IfThen                                                         -- KW["if"] _1 KW["then"] _2 KW["end"],
   SwitchChoiceNoOtherwise                                        -- KW["switch"] _1 _2 KW["end"],
   SwitchChoiceNoOtherwise.2:iter-star                            -- _1,
   SwitchChoice                                                   -- KW["switch"] _1 _2 KW["otherwise"] KW[":"] _3 KW["end"],
   SwitchChoice.2:iter-star                                       -- _1,
   SwitchCase                                                     -- KW["case"] _1 KW[":"] _2,
   AM                                                             -- _1 KW["=>"] _2,
   Assign                                                         -- _1 KW[":="] _2,
   ListVar                                                        -- _1,
   Var                                                            -- _1,
   BuildDefaultPT                                                 -- KW["_"] _1,
   BuildDefault                                                   -- KW["_"] _1,
   Char                                                           -- _1,
   AnnoList                                                       -- _1 KW["{"] _2 KW["}"],
   AnnoList.2:iter-star-sep                                       -- _1 KW[","],
   NoAnnoList                                                     -- _1,
   App                                                            -- KW["<"] _1 KW[">"] _2,
   App                                                            -- KW["<"] _1 KW[">"] _2,
   RootApp                                                        -- _1,
   RootApp                                                        -- _1,
   Tuple                                                          -- KW["("] _1 KW[")"],
   Tuple.1:iter-star-sep                                          -- _1 KW[","],
   List                                                           -- KW["["] _1 KW["]"],
   List.1:iter-star-sep                                           -- _1 KW[","],
   ListTail                                                       -- KW["["] _1 KW["|"] _2 KW["]"],
   ListTail.1:iter-star-sep                                       -- _1 KW[","],
   SortList                                                       -- KW["["] _1 KW["]"],
   SortList.1:iter-star-sep                                       -- _1 KW[","],
   SortListTl                                                     -- KW["["] _1 KW["|"] _2 KW["]"],
   SortListTl.1:iter-star-sep                                     -- _1 KW[","],
   SortTuple                                                      -- KW["("] _1 KW[")"],
   SortTuple.1:iter-star-sep                                      -- _1 KW[","],
   Star                                                           -- KW["*"],
   StarStar                                                       -- KW["**"],
   Sorts                                                          -- V  [H  [KW["sorts"]] _1],
   Sorts.1:iter-star                                              -- _1,
   Constructors                                                   -- V  [H  [KW["constructors"]] _1],
   Constructors.1:iter-star                                       -- _1,
   SortVar                                                        -- _1,
   SortNoArgs                                                     -- _1,
   Sort                                                           -- _1 KW["("] _2 KW[")"],
   Sort.2:iter-star-sep                                           -- _1 KW[","],
   OpDecl                                                         -- _1 KW[":"] _2,
   OpDeclQ                                                        -- _1 KW[":"] _2,
   OpDeclInj                                                      -- KW[":"] _1,
   ExtOpDecl                                                      -- KW["external"] _1 KW[":"] _2,
   ExtOpDeclQ                                                     -- KW["external"] _1 KW[":"] _2,
   ExtOpDeclInj                                                   -- KW["external"] KW[":"] _1,
   ConstType                                                      -- _1,
   FunType                                                        -- _1 KW["->"] _2,
   FunType.1:iter-sep                                             -- _1 KW["*"],
   Var                                                            -- _1,
   Wld                                                            -- KW["_"],
   Int                                                            -- _1,
   Real                                                           -- _1,
   Str                                                            -- _1,
   Op                                                             -- _1 KW["("] _2 KW[")"],
   Op.2:iter-star-sep                                             -- _1 KW[","],
   OpQ                                                            -- _1 KW["("] _2 KW[")"],
   OpQ.2:iter-star-sep                                            -- _1 KW[","],
   Explode                                                        -- _1 KW["#"] KW["("] _2 KW[")"],
   Anno                                                           -- _1 KW["{^"] _2 KW["}"],
   As                                                             -- _1 KW["@"] _2,
   As                                                             -- _1 KW["@"] _2,
   SVar                                                           -- _1,
   Let                                                            -- KW["let"] _1 KW["in"] _2 KW["end"],
   Let.1:iter-star                                                -- _1,
   CallT                                                          -- _1 KW["("] _2 KW["|"] _3 KW[")"],
   CallT.2:iter-star-sep                                          -- _1 KW[","],
   CallT.3:iter-star-sep                                          -- _1 KW[","],
   CallDynamic                                                    -- KW["call"] KW["("] _1 KW["|"] _2 KW["|"] _3 KW[")"],
   CallDynamic.2:iter-star-sep                                    -- _1 KW[","],
   CallDynamic.3:iter-star-sep                                    -- _1 KW[","],
   SDefT                                                          -- _1 KW["("] _2 KW["|"] _3 KW[")"] KW["="] _4,
   SDefT.2:iter-star-sep                                          -- _1 KW[","],
   SDefT.3:iter-star-sep                                          -- _1 KW[","],
   AnnoDef                                                        -- _1 _2,
   AnnoDef.1:iter                                                 -- _1,
   ExtSDefInl                                                     -- KW["external"] _1 KW["("] _2 KW["|"] _3 KW[")"] KW["="] _4,
   ExtSDefInl.2:iter-star-sep                                     -- _1 KW[","],
   ExtSDefInl.3:iter-star-sep                                     -- _1 KW[","],
   ExtSDef                                                        -- KW["external"] _1 KW["("] _2 KW["|"] _3 KW[")"],
   ExtSDef.2:iter-star-sep                                        -- _1 KW[","],
   ExtSDef.3:iter-star-sep                                        -- _1 KW[","],
   ExtSDef                                                        -- KW["external"] _1 KW["("] _2 KW["|"] _3 KW[")"],
   ExtSDef.2:iter-star-sep                                        -- _1 KW[","],
   ExtSDef.3:iter-star-sep                                        -- _1 KW[","],
   Extend                                                         -- KW["extend"],
   Override                                                       -- KW["override"],
   Internal                                                       -- KW["internal"],
   VarDec                                                         -- _1 KW[":"] _2,
   ParenStrat                                                     -- KW["("] _1 KW[")"],
   Fail                                                           -- KW["fail"],
   Id                                                             -- KW["id"],
   ProceedT                                                       -- KW["proceed"] KW["("] _1 KW["|"] _2 KW[")"],
   ProceedT.1:iter-star-sep                                       -- _1 KW[","],
   ProceedT.2:iter-star-sep                                       -- _1 KW[","],
   ProceedNoArgs                                                  -- KW["proceed"],
   Match                                                          -- KW["?"] _1,
   Build                                                          -- KW["!"] _1,
   Scope                                                          -- KW["{"] _1 KW[":"] _2 KW["}"],
   Scope.1:iter-star-sep                                          -- _1 KW[","],
   Seq                                                            -- _1 KW[";"] _2,
   GuardedLChoice                                                 -- _1 KW["<"] _2 KW["+"] _3,
   PrimT                                                          -- KW["prim"] KW["("] _1 KW[","] _2 KW["|"] _3 KW[")"],
   PrimT.2:iter-star-sep                                          -- _1 KW[","],
   PrimT.3:iter-star-sep                                          -- _1 KW[","],
   Some                                                           -- KW["some"] KW["("] _1 KW[")"],
   One                                                            -- KW["one"] KW["("] _1 KW[")"],
   All                                                            -- KW["all"] KW["("] _1 KW[")"],
   ImportTerm                                                     -- KW["import-term"] KW["("] _1 KW[")"],
   Module                                                         -- KW["module"] _1 _2,
   Module.2:iter-star                                             -- _1,
   Specification                                                  -- V  [H  [KW["specification"]] _1],
   Specification.1:iter-star                                      -- _1,
   Imports                                                        -- V  [H  [KW["imports"]] _1],
   Imports.1:iter-star                                            -- _1,
   Strategies                                                     -- V  [H  [KW["strategies"]] _1],
   Strategies.1:iter-star                                         -- _1,
   Signature                                                      -- V  [H  [KW["signature"]] _1],
   Signature.1:iter-star                                          -- _1,
   Import                                                         -- _1,
   Rules                                                          -- V  [H  [KW["rules"]] _1],
   Rules.1:iter-star                                              -- _1,
   Overlays                                                       -- V  [H  [KW["overlays"]] _1],
   Overlays.1:iter-star                                           -- _1,
   Attribute                                                      -- _1 KW["("] _2 KW["|"] _3 KW[")"],
   Attribute.2:iter-star-sep                                      -- _1 KW[","],
   Attribute.3:iter-star-sep                                      -- _1 KW[","],
   AttributeNoTerms                                               -- _1 KW["("] _2 KW[")"],
   AttributeNoTerms.2:iter-star-sep                               -- _1 KW[","],
   AttributeNoArgs                                                -- _1,
   Attribute                                                      -- _1 KW["("] _2 KW["|"] _3 KW[")"],
   Attribute.2:iter-star-sep                                      -- _1 KW[","],
   Attribute.3:iter-star-sep                                      -- _1 KW[","],
   AttributeNoTerms                                               -- _1 KW["("] _2 KW[")"],
   AttributeNoTerms.2:iter-star-sep                               -- _1 KW[","],
   AttributeNoArgs                                                -- _1,
   Attribute                                                      -- _1 KW["("] _2 KW["|"] _3 KW[")"],
   Attribute.2:iter-star-sep                                      -- _1 KW[","],
   Attribute.3:iter-star-sep                                      -- _1 KW[","],
   AttributeNoTerms                                               -- _1 KW["("] _2 KW[")"],
   AttributeNoTerms.2:iter-star-sep                               -- _1 KW[","],
   AttributeNoArgs                                                -- _1,
   Decorator                                                      -- _1 KW["("] _2 KW["|"] _3 KW[")"],
   Decorator.2:iter-star-sep                                      -- _1 KW[","],
   Decorator.3:iter-star-sep                                      -- _1 KW[","],
   DecoratorNoTerms                                               -- _1 KW["("] _2 KW[")"],
   DecoratorNoTerms.2:iter-star-sep                               -- _1 KW[","],
   DecoratorNoArgs                                                -- _1,
   AttributeRef                                                   -- _1 KW["."] _2,
   AttributeTerm                                                  -- _1,
   Attributes                                                     -- V  [H  [KW["attributes"]] _1],
   Attributes.1:iter-star                                         -- _1,
   ADecl                                                          -- _1 _2,
   ADecl.2:iter-sep                                               -- _1 KW[","],
   ADef                                                           -- _1 _2 KW["."] _3,
   Type                                                           -- _1 _2 _3,
   Type.2:iter-star                                               -- _1,
   Type                                                           -- _1 _2 _3,
   Type.2:iter-star                                               -- _1,
   ADefStrategy                                                   -- _1 _2 KW["="] _3,
   Eq                                                             -- KW["eq"],
   Def                                                            -- KW["def"],
   Decorator                                                      -- KW["decorator"],
   Child                                                          -- _1 KW["."],
   DotChild                                                       -- KW["."] _1,
   IdChild                                                        -- KW["id"] KW["."],
   DotIdChild                                                     -- KW["."] KW["id"],
   NoChild                                                        -- ,
   NoChild                                                        -- ,
   Sort                                                           -- _1 KW["."],
   NoSort                                                         -- ,
   NoSort                                                         -- ,
   Root                                                           -- KW["root"],
   Decorators                                                     -- V  [H  [KW["decorators"]] _1],
   Decorators.1:iter-star                                         -- _1,
   ADefNoPattern                                                  -- _1 _2,
   ADefTerm                                                       -- _1 _2 KW[":="] _3 _4,
   ADefTerm.4:iter-star                                           -- _1,
   NameDefBlock                                                   -- _1 _2 KW[":"] _3,
   NameDefBlock.3:iter                                            -- _1,
   PatternDefBlock                                                -- _1 _2 KW[":"] _3,
   PatternDefBlock.3:iter                                         -- _1,
   ADefTerm                                                       -- _1 _2 KW[":="] _3 _4,
   ADefTerm.4:iter-star                                           -- _1,
   ADefStrategy                                                   -- _1 _2 KW["="] _3,
   APDefTerm                                                      -- _1 _2 KW["->"] _3 _4,
   APDefTerm.4:iter-star                                          -- _1,
   APDefTerm                                                      -- _1 _2 KW["->"] _3 _4,
   APDefTerm.4:iter                                               -- _1,
   Where                                                          -- KW["where"] _1,
   With                                                           -- KW["with"] _1,
   AnonymousRewriteRule                                           -- KW["rewrite"] _1 KW["->"] _2 _3,
   AnonymousRewriteRule.3:iter-star                               -- _1,
   IdTerm                                                         -- KW["id"],
   FailTerm                                                       -- KW["fail"],
   PPTable                                                        -- KW["pp-table"] KW[":"] _1,
   PrettyPrint                                                    -- KW["pretty-print"] KW[":"] _1,
   Refactoring                                                    -- KW["refactoring"] _1 KW[":"] _2 KW["="] _3 _4,
   Refactoring.1:iter-star                                        -- _1,
   Refactoring.4:iter-star                                        -- _1,
   SemanticObserver                                               -- KW["observer"] KW[":"] _1,
   Builder                                                        -- KW["builder"] KW[":"] _1 KW["="] _2 _3,
   Builder.3:iter-star                                            -- _1,
   BuilderCaption                                                 -- KW["builder"] KW["caption"] KW[":"] _1,
   OpenEditor                                                     -- KW["(openeditor)"],
   RealTime                                                       -- KW["(realtime)"],
   Persistent                                                     -- KW["(persistent)"],
   Meta                                                           -- KW["(meta)"],
   Cursor                                                         -- KW["(cursor)"],
   Source                                                         -- KW["(source)"],
   CompletionProposer                                             -- KW["completion"] KW["proposer"] KW[":"] _1,
   IdentifierLexical                                              -- KW["completion"] KW["lexical"] KW[":"] _1,
   IdentifierLexical                                              -- KW["identifier"] KW["lexical"] KW[":"] _1,
   CompletionKeyword                                              -- KW["completion"] KW["keyword"] KW[":"] _1 _2,
   CompletionTemplate                                             -- KW["completion"] KW["template"] KW[":"] _1 _2 _3,
   CompletionTemplate.2:iter                                      -- _1,
   CompletionTemplateWithSort                                     -- KW["completion"] KW["template"] KW[":"] _1 KW["="] _2 _3 _4,
   CompletionTemplateWithSort.3:iter-star                         -- _1,
   CompletionTemplateEx                                           -- KW["completion"] KW["template"] _1 KW[":"] _2 _3 _4,
   CompletionTemplateEx.1:iter-star                               -- _1,
   CompletionTemplateEx.3:iter-star                               -- _1,
   CompletionTemplateEx.4:iter-star                               -- _1,
   CompletionTrigger                                              -- KW["completion"] KW["trigger"] KW[":"] _1 _2,
   CompletionTemplateEx                                           -- KW["completion"] KW["template"] _1 KW[":"] _2 _3 _4,
   CompletionTemplateEx.1:iter-star                               -- _1,
   CompletionTemplateEx.3:iter                                    -- _1,
   CompletionTemplateEx.4:iter-star                               -- _1,
   NoCompletionPrefix                                             -- ,
   CompletionPrefix                                               -- _1 KW["="],
   Placeholder                                                    -- _1,
   Cursor                                                         -- KW["(cursor)"],
   PlaceholderWithSort                                            -- _1 _2 KW[">"],
   None                                                           -- ,
   Disable                                                        -- KW["(disabled)"],
   Disable                                                        -- KW["(disable)"],
   Blank                                                          -- KW["(blank)"],
   Linked                                                         -- KW["(linked)"],
   ReferenceHoverRule                                             -- KW["reference"] _1 KW[":"] _2 _3,
   ReferenceRule                                                  -- KW["reference"] _1 KW[":"] _2,
   HoverRule                                                      -- KW["hover"] _1 KW[":"] _2,
   OccurrenceRule                                                 -- KW["occurrence"] _1 KW[":"] _2,
   ColorRuleAll                                                   -- KW["environment"] _1 KW[":"] _2,
   ColorRule                                                      -- _1 KW[":"] _2,
   ColorRuleAllNamed                                              -- KW["environment"] _1 KW[":"] _2 KW["="] _3,
   ColorRuleNamed                                                 -- _1 KW[":"] _2 KW["="] _3,
   Attribute                                                      -- _1 _2 _3,
   AttributeRef                                                   -- _1,
   Token                                                          -- _1,
   Literal                                                        -- KW["token"] _1,
   TK_IDENTIFIER                                                  -- KW["identifier"],
   TK_NUMBER                                                      -- KW["number"],
   TK_LAYOUT                                                      -- KW["layout"],
   TK_STRING                                                      -- KW["string"],
   TK_KEYWORD                                                     -- KW["keyword"],
   TK_OPERATOR                                                    -- KW["operator"],
   TK_VAR                                                         -- KW["var"],
   TK_ERROR                                                       -- KW["error"],
   TK_UNKNOWN                                                     -- KW["unknown"],
   NORMAL                                                         -- ,
   BOLD                                                           -- KW["bold"],
   ITALIC                                                         -- KW["italic"],
   BOLD_ITALIC                                                    -- KW["bold"] KW["italic"],
   BOLD_ITALIC                                                    -- KW["italic"] KW["bold"],
   ColorDefault                                                   -- KW["_"],
   ColorRGB                                                       -- _1 _2 _3,
   NoColor                                                        -- ,
   ColorDef                                                       -- _1 KW["="] _2,
   OutlineRule                                                    -- _1,
   FoldRule                                                       -- _1 _2,
   FoldRuleAll                                                    -- KW["all"] _1 _2,
   Disable                                                        -- KW["(disable)"],
   Disable                                                        -- KW["(disabled)"],
   Folded                                                         -- KW["(folded)"],
   None                                                           -- ,
   SemanticProvider                                               -- KW["provider"] _1,
   SemanticProvider                                               -- KW["provider"] KW[":"] _1,
   OnSave                                                         -- KW["on"] KW["save"] KW[":"] _1 _2,
   Strategy                                                       -- _1,
   Attribute                                                      -- KW["id"] KW["."] _1,
   None                                                           -- ,
   Values                                                         -- _1,
   Values.1:iter-star-sep                                         -- _1 KW[","],
   LanguageName                                                   -- KW["name"] KW[":"] _1,
   LanguageId                                                     -- KW["id"] KW[":"] _1,
   Extensions                                                     -- KW["extensions"] KW[":"] _1,
   Description                                                    -- KW["description"] KW[":"] _1,
   Table                                                          -- KW["table"] KW[":"] _1,
   TableProvider                                                  -- KW["table"] KW["provider"] KW[":"] _1,
   StartSymbols                                                   -- V  [H  [KW["start"] KW["symbols"] KW[":"]] _1],
   StartSymbols.1:iter-star                                       -- _1,
   StartSymbols                                                   -- KW["start"] KW["symbols"] KW[":"] _1,
   URL                                                            -- KW["url"] KW[":"] _1,
   Extends                                                        -- KW["extends"] KW[":"] _1,
   Aliases                                                        -- KW["aliases"] KW[":"] _1,
   UnmanagedTablePrefix                                           -- KW["unmanaged"] KW["table"] KW[":"] _1 KW["*"],
   Disambiguator                                                  -- KW["disambiguator"] KW[":"] _1,
   LineCommentPrefix                                              -- KW["line"] KW["comment"] KW[":"] _1,
   BlockCommentDefs                                               -- KW["block"] KW["comment"] KW[":"] _1,
   FenceDefs                                                      -- V  [H  [KW["fences"] KW[":"]] _1],
   FenceDefs.1:iter-star                                          -- _1,
   IndentDefs                                                     -- V  [H  [KW["indent"] KW["after"] KW[":"]] _1],
   IndentDefs.1:iter-star                                         -- _1,
   IdentifierLexical                                              -- KW["identifier"] KW["lexical"] KW[":"] _1,
   BlockCommentDef                                                -- _1 _2 _3,
   BlockCommentDef                                                -- _1 _2 _3,
   NoContinuation                                                 -- ,
   FenceDef                                                       -- _1 _2,
   IndentDef                                                      -- _1,
   Sort                                                           -- _1,
   ListSort                                                       -- _1 KW["*"],
   String                                                         -- _1,
   ConstructorOnly                                                -- KW["_"] KW["."] _1,
   Constructor                                                    -- _1,
   SortAndConstructor                                             -- _1 KW["."] _2,
   Module                                                         -- KW["module"] _1 _2 _3,
   Module.3:iter-star                                             -- _1,
   Imports                                                        -- V  [H  [KW["imports"]] _1],
   Imports.1:iter                                                 -- _1,
   NoImports                                                      -- ,
   Import                                                         -- _1,
   ImportRenamed                                                  -- _1 KW["["] _2 KW["]"],
   WATER                                                          -- _1,
   WATER                                                          -- _1,
   WATER                                                          -- _1,
   TemplateOptions                                                -- V  [H  [KW["template"] KW["options"]] _1],
   TemplateOptions.1:iter-star                                    -- _1,
   Newlines                                                       -- KW["newlines"] KW[":"] _1,
   None                                                           -- KW["none"],
   Leading                                                        -- KW["leading"],
   Trailing                                                       -- KW["trailing"],
   Separating                                                     -- KW["separating"],
   KeywordFollowRestriction                                       -- KW["keyword"] KW["-/-"] _1,
   KeywordFollowRestriction.1:parameterized-sort                  -- _1 _2,
   KeywordFollowRestriction.1:parameterized-sort.1:"Lookaheads"   -- ,
   simple-ref-group                                               -- _1,
   prods-ref-group                                                -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   prods-ref-group.1:iter                                         -- _1,
   assoc-ref-group                                                -- KW["{"] _1 KW[":"] _2 KW["}"],
   assoc-ref-group.1:parameterized-sort                           -- _1 _2,
   assoc-ref-group.1:parameterized-sort.1:"Associativity"         -- ,
   assoc-ref-group.2:iter                                         -- _1,
   TemplateSection                                                -- V  [H  [KW["templates"]] _1],
   TemplateSection.1:iter-star                                    -- _1,
   lexical-syntax                                                 -- V  [H  [KW["lexical"] KW["syntax"]] _1],
   lexical-syntax.1:iter-star                                     -- _1,
   context-free-syntax                                            -- V  [H  [KW["context-free"] KW["syntax"]] _1],
   context-free-syntax.1:iter-star                                -- _1,
   SdfProduction                                                  -- _1 KW["="] _2 _3,
   SdfProduction.2:parameterized-sort                             -- _1 _2,
   SdfProduction.2:parameterized-sort.1:"Symbols"                 -- ,
   SdfProduction.3:parameterized-sort                             -- _1 _2,
   SdfProduction.3:parameterized-sort.1:"Attributes"              -- ,
   SdfProductionWithCons                                          -- _1 KW["="] _2 _3,
   SdfProductionWithCons.2:parameterized-sort                     -- _1 _2,
   SdfProductionWithCons.2:parameterized-sort.1:"Symbols"         -- ,
   SdfProductionWithCons.3:parameterized-sort                     -- _1 _2,
   SdfProductionWithCons.3:parameterized-sort.1:"Attributes"      -- ,
   TemplateProduction                                             -- _1 KW["="] _2 _3,
   TemplateProduction.3:parameterized-sort                        -- _1 _2,
   TemplateProduction.3:parameterized-sort.1:"Attributes"         -- ,
   TemplateProductionWithCons                                     -- _1 KW["="] _2 _3,
   TemplateProductionWithCons.3:parameterized-sort                -- _1 _2,
   TemplateProductionWithCons.3:parameterized-sort.1:"Attributes" -- ,
   SortCons                                                       -- _1 KW["."] _2,
   Placeholder                                                    -- _1 _2 _3,
   sort                                                           -- _1,
   None                                                           -- ,
   Star                                                           -- KW["*"],
   Plus                                                           -- KW["+"],
   Option                                                         -- KW["?"],
   NoOptions                                                      -- ,
   Options                                                        -- V  [H  [KW[";"]] _1],
   Options.1:iter-sep                                             -- _1 KW[","],
   Hide                                                           -- KW["hide"],
   Wrap                                                           -- KW["wrap"],
   Anchor                                                         -- KW["anchor"],
   Separator                                                      -- KW["separator"] KW["="] _1,
   Text                                                           -- KW["text"] KW["="] _1,
   namespacedef                                                   -- _1 KW["@="] _2,
   namespacedef.2:parameterized-sort                              -- _1 _2,
   namespacedef.2:parameterized-sort.1:"Symbol"                   -- ,
   Concepts                                                       -- V  [H  [KW["concepts"]] _1],
   Concepts.1:iter-star                                           -- _1,
   ConceptDef                                                     -- KW["concept"] _1 KW[":"] _2,
   RuleDef                                                        -- KW["rule"] _1 KW[":"] _2,
   RuleDef.2:iter-star                                            -- _1,
   Rule1                                                          -- _1,
   Rule2                                                          -- _1 KW["->"] _2,
   Main                                                           -- KW["main"],
   CompilationUnit                                                -- _1 _2,
   CompilationUnit.1:iter-star                                    -- _1,
   CompilationUnit.2:iter-star                                    -- _1,
   CompilationUnit                                                -- _1,
   CompilationUnit.1:iter-star                                    -- _1,
   Package                                                        -- KW["package"] _1 _2,
   Package.2:iter-star                                            -- _1,
   Module                                                         -- _1 KW["module"] _2 _3,
   Module.1:opt                                                   -- _1,
   Module.3:iter-star                                             -- _1,
   Module                                                         -- _1 KW["concept"] _2 _3,
   Module.1:opt                                                   -- _1,
   Module.3:iter-star                                             -- _1,
   SDFSection                                                     -- _1,
   SDFSection.1:parameterized-sort                                -- _1 _2,
   SDFSection.1:parameterized-sort.1:"Grammar"                    -- ,
   STRSection                                                     -- _1,
   STRSection.1:parameterized-sort                                -- _1 _2,
   STRSection.1:parameterized-sort.1:"Decl"                       -- ,
   ESVSection                                                     -- _1,
   ESVSection.1:parameterized-sort                                -- _1 _2,
   ESVSection.1:parameterized-sort.1:"Section"                    -- ,
   SDFSectionEH                                                   -- _1 _2,
   SDFSectionEH.2:parameterized-sort                              -- _1 _2,
   SDFSectionEH.2:parameterized-sort.1:"Grammar"                  -- ,
   Exports                                                        -- KW["exports"],
   Hiddens                                                        -- KW["hiddens"],
   ParamName                                                      -- _1 KW["["] _2 KW["]"],
   ParamName.2:parameterized-sort                                 -- _1 _2,
   ParamName.2:parameterized-sort.1:"Symbols"                     -- ,
   Name                                                           -- _1,
   QName                                                          -- _1,
   QName.1:iter-sep                                               -- _1 KW["."],
   Name                                                           -- _1,
   SPXModuleName                                                  -- _1,
   Imports                                                        -- V  [H  [KW["imports"]] _1],
   Imports.1:iter-star                                            -- _1,
   Imports                                                        -- V  [H  [KW["open"]] _1],
   Imports.1:iter-star                                            -- _1,
   Unimports                                                      -- V  [H  [KW["unimports"]] _1],
   Unimports.1:iter-star                                          -- _1,
   Import                                                         -- _1,
   ImportRetain                                                   -- _1 KW["retain"] _2,
   ImportRetain.2:parameterized-sort                              -- _1 _2,
   ImportRetain.2:parameterized-sort.1:"Renamings"                -- ,
   ImportRename                                                   -- _1 _2,
   ImportRename.2:parameterized-sort                              -- _1 _2,
   ImportRename.2:parameterized-sort.1:"Renamings"                -- ,
   NamespaceImport                                                -- KW["namespace"] _1,
   ImportLegacyArtifact                                           -- _1,
   ImportSpxModule                                                -- _1 KW["::"] _2,
   ImportPackage                                                  -- _1,
   ImportPackageWithAlias                                         -- _1 KW["as"] _2,
   AttributeSection                                               -- KW["["] _1 KW["]"],
   AttributeSection.1:iter-sep                                    -- _1 KW[","],
   Target                                                         -- _1,
   Argument-Name                                                  -- _1,
   Positional-argument                                            -- _1 _2,
   Positional-argument.1:opt                                      -- _1,
   Positional-argument                                            -- _1,
   Named-argument                                                 -- _1 KW["="] _2,
   Constructor                                                    -- _1,
   InternalStrategies                                             -- V  [H  [KW["internal"] KW["strategies"]] _1],
   InternalStrategies.1:iter-star                                 -- _1,
   InternalStrategies.1:iter-star.1:parameterized-sort            -- _1 _2,
   InternalStrategies.1:iter-star.1:parameterized-sort.1:"Def"    -- ,
   InternalRules                                                  -- V  [H  [KW["internal"] KW["rules"]] _1],
   InternalRules.1:iter-star                                      -- _1,
   InternalRules.1:iter-star.1:parameterized-sort                 -- _1 _2,
   InternalRules.1:iter-star.1:parameterized-sort.1:"Def"         -- ,
   VarWithType                                                    -- _1 KW["as"] _2,
   VarWithType.1:parameterized-sort                               -- _1 _2,
   VarWithType.1:parameterized-sort.1:"Var"                       -- ,
   QualifiedSVar                                                  -- _1 KW["."] _2,
   QualifiedSVar.2:parameterized-sort                             -- _1 _2,
   QualifiedSVar.2:parameterized-sort.1:"Id"                      -- ,
   QualifiedSort                                                  -- _1 KW["."] _2,
   QualifiedSort.2:parameterized-sort                             -- _1 _2,
   QualifiedSort.2:parameterized-sort.1:"Sort"                    -- ,
   KeywordSection                                                 -- KW["language restrictions"] _1 _2 _3,
   KeywordSection.3:opt                                           -- _1,
   KeywordSymbols                                                 -- V  [H  [KW["rejectsTo"]] _1],
   KeywordSymbols.1:iter                                          -- _1,
   KeywordSymbols.1:iter.1:parameterized-sort                     -- _1 _2,
   KeywordSymbols.1:iter.1:parameterized-sort.1:"Symbol"          -- ,
   Keywords                                                       -- V  [H  [KW["keywords"]] _1],
   Keywords.1:iter                                                -- _1,
   FollowRestriction                                              -- KW["-/-"] _1,
   FollowRestriction.1:parameterized-sort                         -- _1 _2,
   FollowRestriction.1:parameterized-sort.1:"Lookaheads"          -- 
]