[
   Configuration              -- V  [H  [KW["configuration"]] _1],
   Configuration.1:iter-star  -- _1,
   Includes                   -- V  [H  [KW["src"] KW[":"]] _1],
   Includes.1:iter            -- _1,
   Source                     -- _1 _2,
   SpxProjects                -- V  [H  [KW["projectreferences"] KW[":"]] _1],
   SpxProjects.1:iter-star    -- _1,
   Debug                      -- V  [H  [KW["log"] KW[":"]] _1],
   Debug.1:iter-star-sep      -- _1 KW[","],
   TemplateLang               -- KW["templatelang"] KW[":"] _1,
   TemplatelangEnabled        -- KW["enabled"],
   TemplatelangDisabled       -- KW["disabled"],
   DebugCompiler              -- KW["compiler"],
   DebugDeclaration           -- KW["declaration"],
   DebugAnalysis              -- KW["analysis"],
   DebugSymbolTable           -- KW["symboltable"],
   DebugAll                   -- KW["all"],
   DebugNone                  -- KW["none"],
   CodeGeneration             -- V  [H  [KW["codegen:"]] _1],
   CodeGeneration.1:iter-star -- _1,
   OutputDirectory            -- KW["todir"] KW[":"] _1,
   STROutputMode              -- KW["stroutputmode"] KW[":"] _1,
   CTree                      -- KW["ctree"],
   Jar                        -- KW["jar"],
   All                        -- KW["|"] KW["**"],
   ThisOnly                   -- KW["|"] KW["."]
]