[
   PPTable                                -- KW["pp-table"] KW[":"] _1,
   PrettyPrint                            -- KW["pretty-print"] KW[":"] _1,
   Refactoring                            -- KW["refactoring"] _1 KW[":"] _2 KW["="] _3 _4,
   Refactoring.1:iter-star                -- _1,
   Refactoring.4:iter-star                -- _1,
   SemanticObserver                       -- KW["observer"] KW[":"] _1,
   Builder                                -- KW["builder"] KW[":"] _1 KW["="] _2 _3,
   Builder.3:iter-star                    -- _1,
   BuilderCaption                         -- KW["builder"] KW["caption"] KW[":"] _1,
   OpenEditor                             -- KW["(openeditor)"],
   RealTime                               -- KW["(realtime)"],
   Persistent                             -- KW["(persistent)"],
   Meta                                   -- KW["(meta)"],
   Cursor                                 -- KW["(cursor)"],
   Source                                 -- KW["(source)"],
   CompletionProposer                     -- KW["completion"] KW["proposer"] KW[":"] _1,
   IdentifierLexical                      -- KW["completion"] KW["lexical"] KW[":"] _1,
   IdentifierLexical                      -- KW["identifier"] KW["lexical"] KW[":"] _1,
   CompletionKeyword                      -- KW["completion"] KW["keyword"] KW[":"] _1 _2,
   CompletionTemplate                     -- KW["completion"] KW["template"] KW[":"] _1 _2 _3,
   CompletionTemplate.2:iter              -- _1,
   CompletionTemplateWithSort             -- KW["completion"] KW["template"] KW[":"] _1 KW["="] _2 _3 _4,
   CompletionTemplateWithSort.3:iter-star -- _1,
   CompletionTemplateEx                   -- KW["completion"] KW["template"] _1 KW[":"] _2 _3 _4,
   CompletionTemplateEx.1:iter-star       -- _1,
   CompletionTemplateEx.3:iter-star       -- _1,
   CompletionTemplateEx.4:iter-star       -- _1,
   CompletionTrigger                      -- KW["completion"] KW["trigger"] KW[":"] _1 _2,
   CompletionTemplateEx                   -- KW["completion"] KW["template"] _1 KW[":"] _2 _3 _4,
   CompletionTemplateEx.1:iter-star       -- _1,
   CompletionTemplateEx.3:iter            -- _1,
   CompletionTemplateEx.4:iter-star       -- _1,
   NoCompletionPrefix                     -- ,
   CompletionPrefix                       -- _1 KW["="],
   Placeholder                            -- _1,
   Cursor                                 -- KW["(cursor)"],
   PlaceholderWithSort                    -- _1 _2 KW[">"],
   None                                   -- ,
   Disable                                -- KW["(disabled)"],
   Disable                                -- KW["(disable)"],
   Blank                                  -- KW["(blank)"],
   Linked                                 -- KW["(linked)"],
   ReferenceHoverRule                     -- KW["reference"] _1 KW[":"] _2 _3,
   ReferenceRule                          -- KW["reference"] _1 KW[":"] _2,
   HoverRule                              -- KW["hover"] _1 KW[":"] _2,
   OccurrenceRule                         -- KW["occurrence"] _1 KW[":"] _2,
   ColorRuleAll                           -- KW["environment"] _1 KW[":"] _2,
   ColorRule                              -- _1 KW[":"] _2,
   ColorRuleAllNamed                      -- KW["environment"] _1 KW[":"] _2 KW["="] _3,
   ColorRuleNamed                         -- _1 KW[":"] _2 KW["="] _3,
   Attribute                              -- _1 _2 _3,
   AttributeRef                           -- _1,
   Token                                  -- _1,
   Literal                                -- KW["token"] _1,
   TK_IDENTIFIER                          -- KW["identifier"],
   TK_NUMBER                              -- KW["number"],
   TK_LAYOUT                              -- KW["layout"],
   TK_STRING                              -- KW["string"],
   TK_KEYWORD                             -- KW["keyword"],
   TK_OPERATOR                            -- KW["operator"],
   TK_VAR                                 -- KW["var"],
   TK_ERROR                               -- KW["error"],
   TK_UNKNOWN                             -- KW["unknown"],
   NORMAL                                 -- ,
   BOLD                                   -- KW["bold"],
   ITALIC                                 -- KW["italic"],
   BOLD_ITALIC                            -- KW["bold"] KW["italic"],
   BOLD_ITALIC                            -- KW["italic"] KW["bold"],
   ColorDefault                           -- KW["_"],
   ColorRGB                               -- _1 _2 _3,
   NoColor                                -- ,
   ColorDef                               -- _1 KW["="] _2,
   OutlineRule                            -- _1,
   FoldRule                               -- _1 _2,
   FoldRuleAll                            -- KW["all"] _1 _2,
   Disable                                -- KW["(disable)"],
   Disable                                -- KW["(disabled)"],
   Folded                                 -- KW["(folded)"],
   None                                   -- ,
   SemanticProvider                       -- KW["provider"] _1,
   SemanticProvider                       -- KW["provider"] KW[":"] _1,
   OnSave                                 -- KW["on"] KW["save"] KW[":"] _1 _2,
   Strategy                               -- _1,
   Attribute                              -- KW["id"] KW["."] _1,
   None                                   -- ,
   Values                                 -- _1,
   Values.1:iter-star-sep                 -- _1 KW[","],
   LanguageName                           -- KW["name"] KW[":"] _1,
   LanguageId                             -- KW["id"] KW[":"] _1,
   Extensions                             -- KW["extensions"] KW[":"] _1,
   Description                            -- KW["description"] KW[":"] _1,
   Table                                  -- KW["table"] KW[":"] _1,
   TableProvider                          -- KW["table"] KW["provider"] KW[":"] _1,
   StartSymbols                           -- V  [H  [KW["start"] KW["symbols"] KW[":"]] _1],
   StartSymbols.1:iter-star               -- _1,
   StartSymbols                           -- KW["start"] KW["symbols"] KW[":"] _1,
   URL                                    -- KW["url"] KW[":"] _1,
   Extends                                -- KW["extends"] KW[":"] _1,
   Aliases                                -- KW["aliases"] KW[":"] _1,
   UnmanagedTablePrefix                   -- KW["unmanaged"] KW["table"] KW[":"] _1 KW["*"],
   Disambiguator                          -- KW["disambiguator"] KW[":"] _1,
   LineCommentPrefix                      -- KW["line"] KW["comment"] KW[":"] _1,
   BlockCommentDefs                       -- KW["block"] KW["comment"] KW[":"] _1,
   FenceDefs                              -- V  [H  [KW["fences"] KW[":"]] _1],
   FenceDefs.1:iter-star                  -- _1,
   IndentDefs                             -- V  [H  [KW["indent"] KW["after"] KW[":"]] _1],
   IndentDefs.1:iter-star                 -- _1,
   IdentifierLexical                      -- KW["identifier"] KW["lexical"] KW[":"] _1,
   BlockCommentDef                        -- _1 _2 _3,
   BlockCommentDef                        -- _1 _2 _3,
   NoContinuation                         -- ,
   FenceDef                               -- _1 _2,
   IndentDef                              -- _1,
   Sort                                   -- _1,
   ListSort                               -- _1 KW["*"],
   String                                 -- _1,
   ConstructorOnly                        -- KW["_"] KW["."] _1,
   Constructor                            -- _1,
   SortAndConstructor                     -- _1 KW["."] _2,
   Module                                 -- KW["module"] _1 _2 _3,
   Module.3:iter-star                     -- _1,
   Imports                                -- V  [H  [KW["imports"]] _1],
   Imports.1:iter                         -- _1,
   NoImports                              -- ,
   Import                                 -- _1,
   ImportRenamed                          -- _1 KW["["] _2 KW["]"]
]