[
   Program                -- _1 _2,
   Program.2:iter-star    -- _1,
   MainClass              -- KW["class"] _1 KW["{"] _2 KW["}"],
   MainMethod             -- KW["public"] KW["static"] _1 _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   MParam                 -- _1 _2,
   Void                   -- KW["void"],
   StringArray            -- KW["String"] KW["["] KW["]"],
   Class                  -- KW["class"] _1 _2 KW["{"] _3 _4 KW["}"],
   Class.3:iter-star      -- _1,
   Class.4:iter-star      -- _1,
   None                   -- ,
   Parent                 -- KW["extends"] _1,
   Method                 -- KW["public"] _1 _2 KW["("] _3 KW[")"] KW["{"] _4 _5 KW["return"] _6 KW[";"] KW["}"],
   Method.3:iter-star-sep -- _1 KW[","],
   Method.4:iter-star     -- _1,
   Method.5:iter-star     -- _1,
   Field                  -- _1 _2 KW[";"],
   Var                    -- _1 _2 KW[";"],
   Param                  -- _1 _2,
   Int                    -- KW["int"],
   Bool                   -- KW["boolean"],
   Array                  -- KW["int"] KW["["] KW["]"],
   ClassType              -- _1,
   VarRef                 -- _1,
   Block                  -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   Block.1:iter-star      -- _1,
   Assign                 -- _1 KW["="] _2 KW[";"],
   ArrayAssign            -- _1 KW["["] _2 KW["]"] KW["="] _3 KW[";"],
   If                     -- KW["if"] KW["("] _1 KW[")"] _2 KW["else"] _3,
   While                  -- KW["while"] KW["("] _1 KW[")"] _2,
   Print                  -- KW["System"] KW["."] KW["out"] KW["."] KW["println"] KW["("] _1 KW[")"] KW[";"],
   IntValue               -- _1,
   True                   -- KW["true"],
   False                  -- KW["false"],
   This                   -- KW["this"],
   Not                    -- KW["!"] _1,
   Add                    -- _1 KW["+"] _2,
   Sub                    -- _1 KW["-"] _2,
   Mul                    -- _1 KW["*"] _2,
   Lt                     -- _1 KW["<"] _2,
   And                    -- _1 KW["&&"] _2,
   Call                   -- _1 KW["."] _2 KW["("] _3 KW[")"],
   Call.3:iter-star-sep   -- _1 KW[","],
   ArrayNew               -- KW["new"] KW["int"] KW["["] _1 KW["]"],
   ArrayRef               -- _1 KW["["] _2 KW["]"],
   ArrayLength            -- _1 KW["."] KW["length"],
   New                    -- KW["new"] _1 KW["("] KW[")"]
]